name: Build Droidian Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up debos
      run: |
        sudo apt-get update
        sudo apt-get install -y debos

    - name: Build Droidian image
      run: |
        cd /recipes
        debos kali-base.yaml
